export type CrawlDepth = "terminal_list" | "nested_hub" | "special_topic" | "year_archive";

export type SourceTerminalPolicy = "article_detail_required" | "list_only_reference";

export type SiteModuleConfig = {
  id: string;
  domain: string;
  siteName: string;
  departmentName: string;
  channelGroup: string;
  moduleName: string;
  submoduleName?: string;
  listUrl: string;
  crawlDepth: CrawlDepth;
  unresolved: boolean;
  notes?: string;
  terminalPolicy: SourceTerminalPolicy;
};

export type SiteClassificationConfig = {
  departmentId: string;
  departmentName: string;
  classificationPrinciples: string[];
  sourceTraceFields: string[];
  modules: SiteModuleConfig[];
};

export const mctClassificationConfig: SiteClassificationConfig = {
  departmentId: "ministry-of-culture-and-tourism",
  departmentName: "文化和旅游部",
  classificationPrinciples: [
    "按域名先分站点，再按频道组、栏目、子栏目分层，不直接把所有页面平铺成一个列表。",
    "相同 URL 出现在不同导航入口时，只保留一个真实来源模块，其他入口作为展示别名处理。",
    "抓取时默认以文章详情页作为最终来源，不以部门首页或栏目首页代替文章原网址。",
    "遇到未解决嵌套时，先标记为 nested_hub，后续继续向下探测到最终文章列表页或详情页。",
  ],
  sourceTraceFields: [
    "site_name",
    "site_domain",
    "channel_group",
    "module_name",
    "submodule_name",
    "list_url",
    "detail_url",
    "detail_title",
    "breadcrumb",
    "captured_at",
  ],
  modules: [
    {
      id: "mct-www-szyw",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "时政要闻",
      listUrl: "https://www.mct.gov.cn/whzx/szyw/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-whyw",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "焦点新闻",
      listUrl: "https://www.mct.gov.cn/whzx/whyw/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-ldhd",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "领导活动",
      listUrl: "https://www.mct.gov.cn/whzx/ldhd/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-bnsj",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "工作信息",
      listUrl: "https://www.mct.gov.cn/whzx/bnsj/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-djgz",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "党建工作",
      listUrl: "https://www.mct.gov.cn/preview/special/9700/",
      crawlDepth: "special_topic",
      unresolved: true,
      notes: "专题页形态，通常不是最终文章列表，需要继续识别专题内栏目或详情链接。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-zsdw",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "直属单位",
      listUrl: "https://www.mct.gov.cn/whzx/zsdw/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-qgwhxxlb",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "全国联播",
      listUrl: "https://www.mct.gov.cn/whzx/qgwhxxlb/",
      crawlDepth: "nested_hub",
      unresolved: true,
      notes: "可能仍需进一步进入省市联播列表或详情页。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-rdzt",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "热点专题",
      listUrl: "https://www.mct.gov.cn/whzx/rdzt/",
      crawlDepth: "special_topic",
      unresolved: true,
      notes: "专题聚合页，需要拆到专题子页或专题文章详情页。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-tpxw",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "图片新闻",
      listUrl: "https://www.mct.gov.cn/whzx/tpxw/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-zxgz",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "文旅资讯",
      moduleName: "专项工作",
      listUrl: "https://www.mct.gov.cn/whzx/zxgz/",
      crawlDepth: "nested_hub",
      unresolved: true,
      notes: "往往会进入专项工作子专题，不一定是终态列表。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-guide",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开",
      moduleName: "政府信息公开指南",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkzn/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-rule",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开",
      moduleName: "政府信息公开制度",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkzd/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-jggk",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "机构概况",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/jggk/",
      crawlDepth: "nested_hub",
      unresolved: false,
      notes: "该节点本身为目录页，下挂机构职能、领导简介、机构设置、联系我们。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-jgzn",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "机构概况-机构职能",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/jggk/jgzn/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-ldjj",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "机构概况-领导简介",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/jggk/ldjj/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-jgsz",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "机构概况-机构设置",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/jggk/jgsz/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-lxwm",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "机构概况-联系我们",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/jggk/lxwm/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-tjxx",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "统计信息",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/465/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-xzxk",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "行政权力-行政许可",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/466/468/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-sfxm",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "行政权力-行政事业性收费项目",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/466/470/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-hybz",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "行业标准",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/471/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-zwgk",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "综合管理-政务公开",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/472/475/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-jyta",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "综合管理-建议提案答复",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/472/476/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-gwyzk",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "人事信息-公务员招考录用",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/480/481/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-rcgl",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "人事信息-人才管理",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/480/482/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-ysjs",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "财务信息-预算决算",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/483/484/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-cgxx",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "财务信息-政府集中采购",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/483/486/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-wysy",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "文艺事业",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/488/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-ggfw",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "公共服务",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/489/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-kjjy",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "科技教育",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/490/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-fwzwhyc",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "非物质文化遗产",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/491/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-cyfz",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "产业发展",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/494/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-zykf",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "资源开发",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/495/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-scgl",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "市场管理",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/496/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-zhzf",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "文化市场综合执法",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/522/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-jlhz",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "交流合作",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/518/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-topic-other",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "主题分类",
      submoduleName: "其他",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/447/521/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-jyjd",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "决议决定",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/504/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-bl",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "部令",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/505/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-gb",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "公报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/506/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-gg",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "公告",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/507/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-tg",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "通告",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/508/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-yj",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "意见",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/509/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-tz",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "通知",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/510/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-tb",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "通报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/511/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-bg",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "报告",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/512/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-pf",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "批复",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/513/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-han",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "函",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/514/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-genre-other",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开目录",
      moduleName: "体裁分类",
      submoduleName: "其他",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgkml/503/515/index_3081.html",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2025",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2025 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2025n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2024",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2024 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2024n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2023",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2023 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2023n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2022",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2022 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2022n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2021",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2021 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2021n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-zwgk-report-2020",
      domain: "zwgk.mct.gov.cn",
      siteName: "文化和旅游部政府信息公开站",
      departmentName: "文化和旅游部",
      channelGroup: "政府信息公开年报",
      moduleName: "2020 年报",
      listUrl: "https://zwgk.mct.gov.cn/zfxxgknb/2020n/",
      crawlDepth: "year_archive",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-public-work",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "信息发布",
      moduleName: "工作信息",
      listUrl: "https://www.mct.gov.cn/whzx/bnsj/",
      crawlDepth: "terminal_list",
      unresolved: false,
      notes: "与文旅资讯-工作信息重复，建议在库中做 alias 而不是新模块。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-public-zsdw",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "信息发布",
      moduleName: "直属单位",
      listUrl: "https://www.mct.gov.cn/whzx/bnsj/",
      crawlDepth: "terminal_list",
      unresolved: true,
      notes: "当前填写 URL 与工作信息重复，建议你后续确认是否录入有误。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-public-qglb",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "信息发布",
      moduleName: "全国联播",
      listUrl: "https://www.mct.gov.cn/whzx/qgwhxxlb/",
      crawlDepth: "nested_hub",
      unresolved: true,
      notes: "与文旅资讯-全国联播重复，建议 alias。",
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-public-service",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "信息发布",
      moduleName: "公共服务",
      listUrl: "https://www.mct.gov.cn/ggfw/cxts/",
      crawlDepth: "terminal_list",
      unresolved: false,
      terminalPolicy: "article_detail_required",
    },
    {
      id: "mct-www-interaction",
      domain: "www.mct.gov.cn",
      siteName: "文化和旅游部主站",
      departmentName: "文化和旅游部",
      channelGroup: "互动交流",
      moduleName: "互动交流首页",
      listUrl: "https://www.mct.gov.cn/hdjl/",
      crawlDepth: "nested_hub",
      unresolved: true,
      notes: "通常还会拆为部长信箱、征集调查、在线访谈等子模块。",
      terminalPolicy: "article_detail_required",
    },
  ],
};
